Repository Morvince/AREA, pull requests merged in 2023-03, with the labels that each got.

#144 103 rework visuel des block
  area/package-lock.json
  area/package.json
  area/public/index.html
  area/src/assets/android.png
  area/src/assets/landing.png
  area/src/assets/windows.png
  area/src/components/areas/index.js
  area/src/components/block/blockElements.js
  area/src/components/block/index.js
  area/src/components/buttonBlock/buttonBlockElements.js
  area/src/components/buttonBlock/index.js
  area/src/components/infoBlock/index.js
  area/src/components/infoBlock/infoBlockElements.js
  area/src/components/landing/index.js
  area/src/components/navbar/index.js
  area/src/components/playBox/index.js
  area/src/components/playBox/playBoxElements.js
  area/src/components/servicesbar/index.js
  area/src/components/servicesbar/servicesbarElements.js
  area/src/components/settings/index.js
  area/src/fonts/Calistoga/Calistoga-Regular.ttf
  area/src/fonts/Calistoga/OFL.txt
Labels: Bug, New Feature

#162 47 implement twitter service
  server/config/routes.yaml
  server/src/Controller/TwitterAPIController.php
  server/templates/twitter_api/index.html.twig
Labels: New Feature

#171 [ADD]: download button for apk
  area/src/components/landing/LandingElements.js
  area/src/components/landing/index.js
  area/src/download/app-realease.apk
Labels: New Feature

#174 105 sign page mobile
  client_mobile/App.js
  client_mobile/Navigation.js
  client_mobile/assets/images/gmailIcon.png
  client_mobile/assets/images/googleIcon.png
  client_mobile/assets/images/instagramIcon.png
  client_mobile/package-lock.json
  client_mobile/package.json
  client_mobile/src/api/apiCreatePage.js
  client_mobile/src/api/apiMyAreasPage.js
  client_mobile/src/components/Create/actionsBar/index.js
  client_mobile/src/components/Create/actionsList/index.js
  client_mobile/src/components/Create/servicesBar/index.js
  client_mobile/src/components/Create/sideBar/dropdownlist.js
  client_mobile/src/components/Create/sideBar/index.js
  client_mobile/src/components/Create/styles.js
  client_mobile/src/components/Home/actionsBar/index.js
  client_mobile/src/components/Home/actionsList/index.js
  client_mobile/src/components/Home/styles.js
  client_mobile/src/components/MyAreas/menuBar/index.js
  client_mobile/src/components/MyAreas/sideBar/index.js
  client_mobile/src/components/MyAreas/styles.js
  client_mobile/src/pages/Create.js
  client_mobile/src/pages/EnterIpAddress.js
  client_mobile/src/pages/Home.js
  client_mobile/src/pages/MyAreas.js
  client_mobile/src/pages/SignIn.js
  client_mobile/src/pages/SignUp.js
Labels: New Feature

#177 [PATCH]: patch for group section in readme.md
  README.md
Labels: No Code

#178 145 confirmation mail
  area/src/App.js
  area/src/api/apiConfirmMail.js
  area/src/components/servicesbar/index.js
  area/src/pages/Login.js
  area/src/pages/Sign.js
  area/src/pages/Validate.js
  area/src/pages/WaitingForRegistration.js
  server/src/Controller/UserController.php
Labels: New Feature
